baseURL = 'https://sensational-crepe-a65ead.netlify.app/'
languageCode = "fr-fr"
defaultContentLanguage = "fr"
title = 'TU4EVER'
theme = 'spectral'

[markup.goldmark.renderer]
    unsafe = true


[params]
fancyTitle = '<img height="128" src="/images/logo.png" alt="Logo"/>'
copyright = "TU4EVER"
description = 'TU4EVER est une √©quipe compos√©e de deux personnes qui a pour objectif la pr√©paration et la participation √† des raids en Peugeot 205.'
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]
favicon = "static/favicon.ico"

[taxonomies]
    tag = "tags"
    posts = "posts"

[params.one]
enable = false
title = 'Que trouverez-vous sur ce site ?'
body = '''
Vous trouverez sur ce site diff√©rentes pages concernant notre projet de restauration, l'√©quipage, des articles, et autres.
'''

[[params.one.icon]]
icon = "fa-at"
style = "1"
link = 'presentation'

[[params.one.icon]]
icon = "fa-book"
style = "2"
link = "posts"

[[params.one.icon]]
icon = "fa-dollar"
style = "3"
link = "partenariats"

[params.two]
enable = true

[[params.two.section]]
img = "images/one.png"
title = 'Pr√©sentation'
body = """TU4EVER est une √©quipe compos√©e de deux personnes qui a pour objectif la pr√©paration et la participation √† des raids en Peugeot 205.<br /><br />
Pour r√©aliser cet objectif, nous nous sommes lanc√©s dans le projet TU4EVER afin d'acqu√©rir une voiture, de la restaurer et de la pr√©parer par nos soins. 
Nous avons donc achet√© une Peugeot 205 G√©n√©ration de 1997, motoris√©e par l'embl√©matique bloc TU3M de PSA. 
Apr√®s nos diff√©rentes modifications (que nous avons retrac√©s dans les articles), nous avons particip√© √† l'Alpinaraid qui fut une exp√©rience exceptionnelle.<br /><br />
L'origine du nom TU4EVER provient du code moteur <b>TU</b> √©quipant un grand nombre de v√©hicules des marques Peugeot et Citro√´n (PSA), y compris notre Peugeot 205 1,4L."""

[[params.two.section]]
img = "images/two.png"
title = '√âquipage'
body = """Je m'appelle L√©o B, originaire du Jura et grand amoureux de la montagne dont j'affectionne particuli√®rement les paysages.<br />
Amateur en m√©canique, motard et passionn√© de voitures anciennes, je roule quotidiennement avec le pendant de la Peugeot 205, incompr√©hensiblement rest√© en second plan, 
une Citro√´n AX de 1991. Je suis √©galement adepte de VTT, randonn√©es et voyages.<br />Actuellement en derni√®re ann√©e d'une √©cole d'ing√©nieur informatique en alternance 
dans laquelle j'ai fait la connaissance de L√©o K et o√π ce projet de raid est n√©.<br /><br />Je suis L√©o K, n√© en Alsace, j'ai toujours appr√©ci√© les diff√©rents 
panoramas que cette r√©gion peut offrir. Je suis actuellement en derni√®re ann√©e d'√©cole d'ing√©nieur dans le domaine informatique, dans laquelle j'ai rencontr√© L√©o B 
et nous avons d√©but√© ce projet de raid.<br />J'affectionne particuli√®rement piloter des drones, qu'ils soient stabilis√©s ou non (FPV) et toucher √† l'√©lectronique 
(HiFi vintage, construction de claviers m√©caniques et drones).<br />J'appr√©cie √©galement la m√©canique automobile, domaine dans lequel je souhaiterai progresser et apprendre de nouvelles choses."""

[[params.two.section]]
img = "images/three.png"
title = 'Partenariats'
body = """Notre association est toujours √† la recherche de nouveaux partenaires ! Si vous √™tes une entreprise ou un particulier et que vous souhaitez nous soutenir 
dans ce projet, vous pouvez le faire de plusieurs mani√®res : <ul><li>Financements</li><li>Don de mat√©riel</li><li>Comp√©tences techniques diverses</li><li>Partage du site et de nos r√©seaux sociaux</li></ul>
Pour toutes questions ou demande de partenariats, vous pouvez nous contacter via notre compte <a href='https://instagram.com/tu4ever_205' target='_blank' class='email-highlights'>Instagram</a> 
ou directement √† l'adresse <span class='email-highlights'>partenariats@tu4ever.fr</span>. Nous serons ravis de collaborer avec vous ! 
En contrepartie de votre participation, nous pouvons vous offrir de la visibilit√© sur notre site, sur notre Instagram et directement sur la voiture en apposant votre sticker."""

[params.three]
enable = false
title = 'Accumsan mus tortor nunc aliquet'
body = '''
Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend  
fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.
'''

[[params.three.feature]]
icon = "fa-paper-plane-o"
title = "Arcu accumsan"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-laptop"
title = "Ac Augue Eget"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-code"
title = "Foo bar"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-headphones"
title = "Baz kram"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-heart-o"
title = "Some latin text"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-flag-o"
title = "Nothing important"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[params.cta]
enable = true
title = "Notre derni√®re vid√©o"
body = "Vous retrouverez ici notre chaine Youtube sur laquelle nous postons des vid√©os sur l'aventure."

[[params.cta.link]]
href = "https://www.youtube.com/watch?v=V7fG8VPShmg"
text = "Alpinaraid 22"
special = true

[[params.cta.link]]
href = "https://www.youtube.com/channel/UC0HjHxtWTms3Yz9J8KffR3A"
text = "Youtube"
special = false

[params.contact]
enable = false
title = "Contact"
body = "Leave us a message."
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "contact@tu4ever.fr"
subject = "New Submission!"
plain = false

[params.social]
twitter = "tu4ever_205"
facebook = ""
instagram = "tu4ever_205"
dribble = ""

staticDir = ['images']

# language specific options

[languages]
    [languages.fr]
        weight = 2
        languageName = "Fran√ßais"
        languageShortName = "FR"
        languageFlag = "üá´üá∑"

            [[languages.fr.params.menu.main]]
            url = '/fr/'
            title = "Accueil"

            [[languages.fr.params.menu.main]]
            url = 'posts/'
            title = "Articles"

            [[languages.fr.params.menu.main]]
            url = '/fr/alpinaraid/'
            title = "Alpinaraid 2022"

    [languages.en]
        weight = 1
        languageName = "English"
        languageShortName = "EN"
        languageFlag = "üá∫üá∏"

            [[languages.en.params.menu.main]]
            url = '/en/'
            title = "Home"
            [[languages.en.params.menu.main]]
            url = '/en/posts/'
            title = "Posts"
            [[languages.en.params.menu.main]]
            url = '/en/alpinaraid/'
            title = "Alpinaraid 2022"